import assert from 'node:assert/strict';
import test from 'node:test';
import {resolveSemanticMotion} from '../src/semantic-motion.mjs';
import {resolvePreviewEventPairs} from '../scripts/preview.mjs';
const pen={id:'pen',initial_state:'visible',states:{visible:{transform:{x:620,y:745,width:220,height:115}}}};
const notebook={id:'notebook',initial_state:'visible',states:{visible:{transform:{x:280,y:356,width:520,height:488}}}};
const scene={id:'s07',start_frame:0,duration_frames:40,spatial_bindings:[{entity:'pen',anchor:'notebook',relation:'points_to'}],entities:[pen,notebook]};
const event=motion=>({event_id:'s07_e01',state_before:'visible',state_after:'visible',asset_before:'PROP_PEN',asset_after:'PROP_PEN',motion,target:'pen',start_frame:10,end_frame:21});
test('slide peak moves pen tip to notebook mark',()=>{const m=resolveSemanticMotion(event('slide'),scene,pen,15);assert.ok(m.peak>.99);assert.ok(m.translateY<-150);assert.ok(m.translateX<-30);const tip={x:620+220*18/320+m.translateX,y:745+115*151/160+m.translateY};assert.ok(Math.abs(tip.x-(280+520*.60))<1);assert.ok(Math.abs(tip.y-(356+488*.64))<1);});
test('subtle tilt and bounce are visible only within event',()=>{const actor={id:'gemini',states:{visible:{}}};assert.ok(resolveSemanticMotion(event('subtle-tilt'),scene,actor,15).rotateDeg>=3.4);assert.ok(resolveSemanticMotion(event('small-bounce'),scene,actor,15).translateY<=-19);assert.equal(resolveSemanticMotion(event('small-bounce'),scene,actor,9).translateY,0);});
test('hold does not animate or count as motion only',()=>{const m=resolveSemanticMotion(event('hold'),scene,pen,15);assert.equal(m.translateY,0);assert.equal(m.rotateDeg,0);const p=resolvePreviewEventPairs({...scene,events:[event('hold')]})[0];assert.equal(p.static_hold,true);assert.equal(p.motion_only,false);assert.equal(p.second_role,'after');});
test('identical state_swap is rejected in preview',()=>{assert.throws(()=>resolvePreviewEventPairs({...scene,events:[event('state_swap')]}),/PREVIEW_NOOP_STATE_SWAP/);});
test('slide requires points_to anchor, no fallback',()=>{assert.throws(()=>resolveSemanticMotion(event('slide'),{entities:[pen]},pen,15),/SLIDE_CONTACT_BINDING_REQUIRED/);});
test('active motions are sampled at during frame',()=>{const p=resolvePreviewEventPairs({...scene,events:[event('slide')]})[0];assert.equal(p.second_role,'during');assert.equal(p.second_frame,15);});
